namespaces:
  app: always-open
  istio: istio-system

hosts:
  api: dev.api.bealwaysopen.ai
  app: dev.app.bealwaysopen.ai

gateway:
  name: always-open-gateway
  selector:
    istio: ingress
  tls:
    enabled: false
    credentialName: always-open-tls

apiVirtualService:
  name: always-open-api-routing
  routes:
    - prefix: /api
      host: api-service
      port: 3000
    - prefix: /call
      host: call-manager
      port: 3000
    - prefix: /chat
      host: chat-manager
      port: 3000
    - prefix: /knowledge
      host: knowledge-manager
      port: 8000
    - prefix: /billing
      host: billing-service
      port: 3000
    - prefix: /analysis
      host: analysis-service
      port: 3000
    - prefix: /token
      host: token-manager
      port: 3004
    - prefix: /webhook
      host: webhook-manager
      port: 3000
    - prefix: /integrations/crm
      host: ghl-adapter
      port: 3000
    - prefix: /scheduler
      host: call-scheduler
      port: 3000
    - prefix: /agent
      host: agent-manager
      port: 8000

appVirtualService:
  name: always-open-app-routing
  destination:
    host: always-open-webapp
    port: 80
