{{- if .Values.mtls.enabled }}
{{- range $name, $svc := .Values.internalServices }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $name }}-mtls
  namespace: always-open
spec:
  host: {{ $svc.host | quote }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
{{- end }}
{{- end }}
