apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  init-app-user.js: |
    db = db.getSiblingDB({{ .Values.auth.appDatabase | quote }});
    db.createUser({
      user: {{ .Values.auth.appUsername | quote }},
      pwd: {{ .Values.auth.appPassword | quote }},
      roles: [{ role: "readWrite", db: {{ .Values.auth.appDatabase | quote }} }]
    });
