apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-headless
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
